config/routes.rb
Railsgirlsdirectory::Application.routes.draw do
  resources :individuals

  resources :companies

  resources :addresses

  resources :jobfunctions

end

app/models/individual.rb
class Individual < ActiveRecord::Base
  belongs_to :company
end

app/controllers/individuals_controller.rb
class IndividualsController < ApplicationController
  before_action :set_individual, only: [:show, :edit, :update, :destroy]

  # GET /individuals
  # GET /individuals.json
  def index
    @individuals = Individual.all
  end

  # GET /individuals/1
  # GET /individuals/1.json
  def show
  end

  # GET /individuals/new
  def new
    @individual = Individual.new
  end

  # GET /individuals/1/edit
  def edit
  end

  # POST /individuals
  # POST /individuals.json
  def create
    @individual = Individual.new(individual_params)

    respond_to do |format|
      if @individual.save
        format.html { redirect_to @individual, notice: 'Individual was successfully created.' }
        format.json { render action: 'show', status: :created, location: @individual }
      else
        format.html { render action: 'new' }
        format.json { render json: @individual.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /individuals/1
  # PATCH/PUT /individuals/1.json
  def update
    respond_to do |format|
      if @individual.update(individual_params)
        format.html { redirect_to @individual, notice: 'Individual was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @individual.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /individuals/1
  # DELETE /individuals/1.json
  def destroy
    @individual.destroy
    respond_to do |format|
      format.html { redirect_to individuals_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_individual
      @individual = Individual.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def individual_params
      params.require(:individual).permit(:first_name, :last_name, :website, :email, :company_id)
    end
end

app/helpers/individuals_helper.rb
module IndividualsHelper
end

app/views/individuals/_form.html.erb
<%= form_for(@individual) do |f| %>
  <% if @individual.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@individual.errors.count, "error") %> prohibited this individual from being saved:</h2>

      <ul>
      <% @individual.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br>
    <%= f.text_field :company_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/individuals/edit.html.erb
<h1>Editing individual</h1>

<%= render 'form' %>

<%= link_to 'Show', @individual %> |
<%= link_to 'Back', individuals_path %>

app/views/individuals/index.html.erb
<h1>Listing individuals</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Website</th>
      <th>Email</th>
      <th>Company</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @individuals.each do |individual| %>
      <tr>
        <td><%= individual.first_name %></td>
        <td><%= individual.last_name %></td>
        <td><%= individual.website %></td>
        <td><%= individual.email %></td>
        <td><%= individual.company %></td>
        <td><%= link_to 'Show', individual %></td>
        <td><%= link_to 'Edit', edit_individual_path(individual) %></td>
        <td><%= link_to 'Destroy', individual, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Individual', new_individual_path %>

app/views/individuals/new.html.erb
<h1>New individual</h1>

<%= render 'form' %>

<%= link_to 'Back', individuals_path %>

app/views/individuals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @individual.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @individual.last_name %>
</p>

<p>
  <strong>Website:</strong>
  <%= @individual.website %>
</p>

<p>
  <strong>Email:</strong>
  <%= @individual.email %>
</p>

<p>
  <strong>Company:</strong>
  <%= @individual.company %>
</p>

<%= link_to 'Edit', edit_individual_path(@individual) %> |
<%= link_to 'Back', individuals_path %>