config/routes.rb
Railsgirlsdirectory::Application.routes.draw do
  resources :individuals

  resources :companies

  resources :addresses

  resources :jobfunctions

end

app/models/jobfunction.rb
class Jobfunction < ActiveRecord::Base
end

app/controllers/jobfunctions_controller.rb
class JobfunctionsController < ApplicationController
  before_action :set_jobfunction, only: [:show, :edit, :update, :destroy]

  # GET /jobfunctions
  # GET /jobfunctions.json
  def index
    @jobfunctions = Jobfunction.all
  end

  # GET /jobfunctions/1
  # GET /jobfunctions/1.json
  def show
  end

  # GET /jobfunctions/new
  def new
    @jobfunction = Jobfunction.new
  end

  # GET /jobfunctions/1/edit
  def edit
  end

  # POST /jobfunctions
  # POST /jobfunctions.json
  def create
    @jobfunction = Jobfunction.new(jobfunction_params)

    respond_to do |format|
      if @jobfunction.save
        format.html { redirect_to @jobfunction, notice: 'Jobfunction was successfully created.' }
        format.json { render action: 'show', status: :created, location: @jobfunction }
      else
        format.html { render action: 'new' }
        format.json { render json: @jobfunction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobfunctions/1
  # PATCH/PUT /jobfunctions/1.json
  def update
    respond_to do |format|
      if @jobfunction.update(jobfunction_params)
        format.html { redirect_to @jobfunction, notice: 'Jobfunction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @jobfunction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobfunctions/1
  # DELETE /jobfunctions/1.json
  def destroy
    @jobfunction.destroy
    respond_to do |format|
      format.html { redirect_to jobfunctions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jobfunction
      @jobfunction = Jobfunction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jobfunction_params
      params.require(:jobfunction).permit(:name)
    end
end

app/helpers/jobfunctions_helper.rb
module JobfunctionsHelper
end

app/views/jobfunctions/_form.html.erb
<%= form_for(@jobfunction) do |f| %>
  <% if @jobfunction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@jobfunction.errors.count, "error") %> prohibited this jobfunction from being saved:</h2>

      <ul>
      <% @jobfunction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobfunctions/edit.html.erb
<h1>Editing jobfunction</h1>

<%= render 'form' %>

<%= link_to 'Show', @jobfunction %> |
<%= link_to 'Back', jobfunctions_path %>

app/views/jobfunctions/index.html.erb
<h1>Listing jobfunctions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @jobfunctions.each do |jobfunction| %>
      <tr>
        <td><%= jobfunction.name %></td>
        <td><%= link_to 'Show', jobfunction %></td>
        <td><%= link_to 'Edit', edit_jobfunction_path(jobfunction) %></td>
        <td><%= link_to 'Destroy', jobfunction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Jobfunction', new_jobfunction_path %>

app/views/jobfunctions/new.html.erb
<h1>New jobfunction</h1>

<%= render 'form' %>

<%= link_to 'Back', jobfunctions_path %>

app/views/jobfunctions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @jobfunction.name %>
</p>

<%= link_to 'Edit', edit_jobfunction_path(@jobfunction) %> |
<%= link_to 'Back', jobfunctions_path %>